baseURL = "https://brightprogrammer.in/"
keywords = ["brightprogrammer", "siddharth", "mishra", "misrastdc", "reverse-engineering"]
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2023"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "118%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true
enableInlineShortcodes = true
mermaid = true
palette = "ember"

[sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true
