baseURL = "https://brightprogrammer.in/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
rssLimit = 10
theme = "bright-legacy"
title = "Siddharth Mishra"
enableEmoji = true

[pagination]
pagerSize = 10

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="Siddharth Mishra"
author = "Siddharth Mishra"
description = "Personal blogging and note taking."
footnote = """
<center>
Siddharth Mishra. All Rights Reserved.<br/>
</center>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "150%"
math = true
enableDuckDuckGoSearchBox = false 
numberedSubtitles = true
